routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Generate authentication routes.
Auth::routes(['register' => false, 'verify' => false]);

Route::group(['middleware' => 'auth', 'namespace' => 'Dashboard'], function() {
    // Route related to dashboard.
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

    // Routes related to profile.
    Route::get('/profile', 'ProfileController@edit')->name('profiles.edit');
    Route::put('/profile', 'ProfileController@update')->name('profiles.update');

    Route::group(['middleware' => ['role:superadmin']], function () {
        // Routes related to role.
        Route::get('roles/get', 'RoleController@get')->name('roles.get');
        Route::resource('roles', 'RoleController');

        // Routes related to user.
        Route::patch('users/{user}/api_key', 'UserController@updateApiKey')->name('users.update.api_key');
        Route::get('users/get', 'UserController@get')->name('users.get');
        Route::resource('users', 'UserController');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Laravel\Lumen\Auth\Authorizable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use OwenIt\Auditing\Contracts\Auditable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements Auditable
{
    use Notifiable;
    use HasRoles;
    use \OwenIt\Auditing\Auditable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'api_token', 'email', 'password', 'phone', 'is_active', 'remember_token'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password'
    ];
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateRequest;
use App\Http\Requests\User\EditRequest;
use App\Models\User;
use App\Services\UserService;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use App\Models\Role;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    private $userService;

    /**
     * UserController constructor.
     *
     * @param UserService $userService
     */
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    /**
     * Display list of user available.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('pages.user.index');
    }

    /**
     * Get all user.
     *
     * @return mixed
     * @throws Exception
     */
    public function get()
    {
        return $this->userService->getAllUser();
    }

    /**
     * Show details information of user.
     *
     * @param User $user
     *
     * @return Factory|View
     */
    public function show(User $user)
    {
        $userRoles = generateListElement($user->roles->toArray(), ['name']);

        return view('pages.user.show', compact('user', 'userRoles'));
    }

    /**
     * Form to create new user.
     *
     * @return Factory|View
     */
    public function create()
    {
        $roles = Role::select('name')->get();

        return view('pages.user.create', compact('roles'));
    }

    /**
     * Store new user in database.
     *
     * @param CreateRequest $request
     *
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $result = $this->userService->createNewUser($request->except('_token'));

        if ($result) {
            return redirect()->route('users.index')->with('message', 'Successfully created user ' . $request->username . '.');
        }

        return redirect()->back()->with('error', 'Failed to create user ' . $request->username . '.');
    }

    /**
     * Display form to edit user.
     *
     * @param User $user
     *
     * @return Factory|View
     */
    public function edit(User $user)
    {
        $roles = Role::select('name')->get();

        $userRoles = $user->roles->pluck('name')->toArray();

        return view('pages.user.edit', compact('user', 'roles', 'userRoles'));
    }

    /**
     * Update user information.
     *
     * @param User $user
     * @param EditRequest $request
     *
     * @return void
     */
    public function update(User $user, EditRequest $request)
    {
        $result = $this->userService->updateUser($user, $request->except('_token'));

        if ($result) {
            return redirect()->back()->with('message', 'User has been updated.');
        }

        return redirect()->back()->with('error', 'Failed to update ' . $user->username  . ' user');
    }

    /**
     * Update user API Key using user ID.
     *
     * @param User $user
     *
     * @return JsonResponse
     * @throws Exception
     */
    public function updateApiKey(User $user)
    {
        $result = $this->userService->updateApiKey($user);

        return response()->json($result);
    }

    /**
     * Delete user in database using user ID.
     *
     * @param User $user
     *
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy(User $user)
    {
        $result = $this->userService->deleteUser($user);

        return response()->json($result);
    }
}

resources/views/pages/user/create.blade.php
@extends('layouts.app')

@push('css')
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.5.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <link href="{{ asset('plugins/select2/css/select2.min.css') }}" rel="stylesheet">
@endpush

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Users</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Create New User</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        @if (session('error'))
                                            <div class="alert alert-danger alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('error') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        <form class="form-horizontal" action="{{ route('users.store') }}" method="post">
                                            @csrf

                                            <div class="form-group row">
                                                <label for="username" class="col-sm-2 col-form-label">Username</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="username" name="username" value="{{ old('username') }}" required>
                                                    @error('username')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="email" class="col-sm-2 col-form-label">Email</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="email" id="email" name="email" value="{{ old('email') }}" required>
                                                    @error('email')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="phone" class="col-sm-2 col-form-label">Phone</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="phone" name="phone" value="{{ old('phone') }}">
                                                    @error('phone')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="api_token" class="col-sm-2 col-form-label">API Token</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="api_token" name="api_token" value="{{ old('api_token') }}" required>
                                                    <button type="button" class="mt-2 mb-2 btn btn-primary" id="generate-api-key">Generate</button>
                                                    @error('api_token')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="password_confirmation" class="col-sm-2 col-form-label">Roles</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control select2-roles" name="roles[]" multiple="multiple" data-placeholder="Select roles">
                                                        @foreach ($roles as $role)
                                                            <option value="{{ $role->name }}">{{ $role->name }}</option>
                                                        @endforeach
                                                    </select>
                                                    @error('roles')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="is_active" class="col-sm-2 col-form-label">Active</label>
                                                <div class="col-sm-10">
                                                    <input type="checkbox" data-toggle="toggle" data-size="sm" name="is_active">
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="password" class="col-sm-2 col-form-label">Password</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="password" id="password" name="password" required>
                                                    <small id="password-help" class="form-text text-muted">Password must contain at least one digit, one lowercase character, one uppercase character and one special character.</small>
                                                    <span></span>
                                                    @error('password')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="password_confirmation" class="col-sm-2 col-form-label">Password Confirmation</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="password" id="password_confirmation" name="password_confirmation">
                                                    @error('password_confirmation')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-xs-12">
                                                    <button type="submit" class="btn btn-primary">Create</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@push('js')
    <script src="{{ asset('plugins/select2/js/select2.full.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.5.0/js/bootstrap4-toggle.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2-roles').select2();
        });
    </script>
    <script>
        function generateUUIDv4() {
            return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
                (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
            )
        }

        $('#generate-api-key').click(function () {
            var apiToken = generateUUIDv4();

            $('#api_token').val(apiToken);
        })
    </script>
@endpush

resources/views/pages/user/index.blade.php
@extends('layouts.app')

@push('css')
    <link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Users</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Users</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        @if (session('message'))
                            <div class="alert alert-success alert-dismissible fade show m-t-20 " role="alert">
                                {{ session('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Available Users</h3>
                                    <a href="{{ route('users.create') }}"><button class="btn btn-primary">Create New User</button></a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="user-table">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Username</th>
                                            <th>Email</th>
                                            <th>Roles</th>
                                            <th>Active</th>
                                            <th>API Token</th>
                                            <th>Created At</th>
                                            <th width="130px;">Action</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@push('js')
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
    <script>
        var updateApiKey = function updateApiKey(context) {
            var userID = $(context).attr('data-id');
            var username = $(context).attr('data-username');

            swal({
                title: 'Are you sure want to generate new api key for "' + username + '"?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonClass: 'btn btn-sm btn-success',
                cancelButtonClass: 'btn btn-danger btn-sm m-l-10',
                confirmButtonText: 'Yes!'
            }).then(function (result) {
                if (!result.value) {
                    return;
                }

                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: '/users/' + userID + '/api_key',
                    type: 'PATCH',
                    success: function(result) {
                        if (result) {
                            swal({
                                title: "Success!",
                                text: "Successfully generate api key for " + username,
                                type: "success",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-success',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            }).then(function () {
                                $('.api-key-' + userID).html(result);
                            });
                        } else {
                            swal({
                                title: "Failed!",
                                text: "Failed to generate API key for " + username,
                                type: "error",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-danger',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            });
                        }
                    }
                });
            });
        };

        var deleteUser = function deleteUser(context) {
            var userID = $(context).attr('data-id');
            var username = $(context).attr('data-title');

            swal({
                title: 'Are you sure want to delete user "' + username + '"?',
                text: "You will not be able to recover this user after deleted!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger m-l-10',
                confirmButtonText: 'Yes, delete it!'
            }).then(function (result) {
                if (!result.value) {
                    return;
                }

                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: '/users/' + userID,
                    type: 'DELETE',
                    success: function(result) {
                        if (result) {
                            swal({
                                title: "Deleted!",
                                text: "User " + username + " has been deleted.",
                                type: "success",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-success',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            }).then(function () {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: "Deleting Failed!",
                                text: "Failed to delete user " + username,
                                type: "error",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-danger',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            }).then(function () {
                                location.reload();
                            });
                        }
                    }
                });
            })
        };

        $(function() {
            $('#user-table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                ajax: '{!! route('users.get') !!}',
                columns: [
                    { data: 'id', name: 'id', searchable: false },
                    { data: 'username', name: 'username' },
                    { data: 'email', name: 'email' },
                    { data: 'roles', name: 'roles.name' },
                    { data: 'is_active', name: 'is_active' },
                    { data: 'api_token', name: 'api_token' },
                    { data: 'created_at', name: 'created_at', searchable: false },
                    { data: 'action', name: 'action', orderable: false, searchable: false }
                ],
                drawCallback: function() {
                    $('.delete-btn').on('click', function () {
                        deleteUser(this);
                    });
                    $('.generate-api-key-btn').on('click', function () {
                        updateApiKey(this);
                    });
                }
            });
        });
    </script>
@endpush