routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Generate authentication routes.
Auth::routes(['register' => false, 'verify' => false]);

Route::group(['middleware' => 'auth', 'namespace' => 'Dashboard'], function() {
    // Route related to dashboard.
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

    // Routes related to profile.
    Route::get('/profile', 'ProfileController@edit')->name('profiles.edit');
    Route::put('/profile', 'ProfileController@update')->name('profiles.update');

    Route::group(['middleware' => ['role:superadmin']], function () {
        // Routes related to role.
        Route::get('roles/get', 'RoleController@get')->name('roles.get');
        Route::resource('roles', 'RoleController');

        // Routes related to user.
        Route::patch('users/{user}/api_key', 'UserController@updateApiKey')->name('users.update.api_key');
        Route::get('users/get', 'UserController@get')->name('users.get');
        Route::resource('users', 'UserController');
    });
});

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Profile\EditRequest;
use App\Services\ProfileService;
use Illuminate\Contracts\View\Factory;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class ProfileController extends Controller
{
    /**
     * @var ProfileService
     */
    private $profileService;

    /**
     * ProfileController constructor.
     *
     * @param ProfileService $profileService
     */
    public function __construct(ProfileService $profileService)
    {
        $this->profileService = $profileService;
    }


    /**
     * Display page to edit profile.
     *
     * @return Factory|View
     */
    public function edit()
    {
        $user = Auth::user();

        return view('pages.profile.edit', compact('user'));
    }

    /**
     * Update user profile.
     *
     * @param EditRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EditRequest $request)
    {
        $user = Auth::user();

        $result = $this->profileService->updateProfile($user, $request->except('token'));

        if ($result) {
            return redirect()->back()->with('message', 'Your profile has been updated.');
        }

        return redirect()->back()->with('error', 'Failed to update your profile.');
    }
}

resources/views/pages/profile/edit.blade.php
@extends('layouts.app')

@push('css')
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.5.0/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <link href="{{ asset('plugins/select2/css/select2.min.css') }}" rel="stylesheet">
@endpush

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Users</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                            <li class="breadcrumb-item active">Edit</li>
                        </ol>
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Edit User</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        @if (session('message'))
                                            <div class="alert alert-success alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('message') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        @if (session('error'))
                                            <div class="alert alert-danger alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('error') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        <form class="form-horizontal" action="{{ route('profiles.update') }}" method="post">
                                            @method('PUT')
                                            @csrf

                                            <div class="form-group row">
                                                <label for="username" class="col-sm-2 col-form-label">Username</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="username" name="username" value="{{ old('username') ?: $user->username }}" required>
                                                    @error('username')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="email" class="col-sm-2 col-form-label">Email</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="email" id="email" name="email" value="{{ old('email') ?: $user->email }}" required>
                                                    @error('email')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="phone" class="col-sm-2 col-form-label">Phone</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="phone" name="phone" value="{{ old('phone') ?: $user->phone }}">
                                                    @error('phone')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="password" class="col-sm-2 col-form-label">Password</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="password" id="password" name="password">
                                                    <small id="password-help" class="form-text text-muted">Password minimum length is 14 and must contain at least one digit, one lowercase character, one uppercase character and one special character.</small>
                                                    @error('password')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label for="password_confirmation" class="col-sm-2 col-form-label">Password Confirmation</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="password" id="password_confirmation" name="password_confirmation">
                                                    @error('password_confirmation')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-xs-12">
                                                    <button type="submit" class="btn btn-primary">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@push('js')
    <script src="{{ asset('plugins/select2/js/select2.full.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.5.0/js/bootstrap4-toggle.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2-roles').select2();
        });
    </script>
    <script>
        $(document).ready(function() {
            $('.select2-roles').select2();
        });
    </script>
    <script>
        function generateUUIDv4() {
            return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
                (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
            )
        }

        $('#generate-api-key').click(function (event) {
            event.preventDefault();
            var apiToken = generateUUIDv4();

            $('#api_token').val(apiToken);
        })
    </script>

@endpush