routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Generate authentication routes.
Auth::routes(['register' => false, 'verify' => false]);

Route::group(['middleware' => 'auth', 'namespace' => 'Dashboard'], function() {
    // Route related to dashboard.
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

    // Routes related to profile.
    Route::get('/profile', 'ProfileController@edit')->name('profiles.edit');
    Route::put('/profile', 'ProfileController@update')->name('profiles.update');

    Route::group(['middleware' => ['role:superadmin']], function () {
        // Routes related to role.
        Route::get('roles/get', 'RoleController@get')->name('roles.get');
        Route::resource('roles', 'RoleController');

        // Routes related to user.
        Route::patch('users/{user}/api_key', 'UserController@updateApiKey')->name('users.update.api_key');
        Route::get('users/get', 'UserController@get')->name('users.get');
        Route::resource('users', 'UserController');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use OwenIt\Auditing\Contracts\Auditable;

class Role extends \Spatie\Permission\Models\Role implements Auditable
{
    use \OwenIt\Auditing\Auditable;
}

app/Http/Controllers/Dashboard/RoleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Role\CreateRequest;
use App\Http\Requests\Role\EditRequest;
use App\Services\RoleService;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use App\Models\Role;

class RoleController extends Controller
{
    /**
     * @var RoleService
     */
    private $roleService;

    /**
     * RoleController constructor.
     *
     * @param RoleService $roleService
     */
    public function __construct(RoleService $roleService)
    {
      $this->roleService = $roleService;
    }

    /**
     * Display list of role available.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('pages.role.index');
    }

    /**
     * Get all role.
     *
     * @return mixed
     * @throws Exception
     */
    public function get()
    {
        return $this->roleService->getAllRole();
    }

    /**
     * Page to create new role.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('pages.role.create');
    }

    /**
     * Store new role in database.
     *
     * @param CreateRequest $request
     *
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $result = $this->roleService->createNewRole($request->except('_token'));

        if ($result) {
            return redirect()->route('roles.index')->with('message', 'Successfully created role ' . $request->name . '.');
        }

        return redirect()->back()->with('error', 'Failed to create role ' . $request->name . '.');
    }

    /**
     * Display page to edit role.
     *
     * @param Role $role
     *
     * @return Factory|View
     */
    public function edit(Role $role)
    {
        return view('pages.role.edit', compact('role'));
    }

    /**
     * Update role information in database.
     *
     * @param Role $role
     * @param EditRequest $request
     *
     * @return void
     */
    public function update(Role $role, EditRequest $request)
    {
        $result = $this->roleService->updateRole($role, $request->except('_token'));

        if ($result) {
            return redirect()->back()->with('message',  'Role has been updated.');
        }

        return redirect()->back()->with('error', 'Failed to update ' . $role->name  . ' role');
    }

    /**
     * Delete role in database using role ID.
     *
     * @param Role $role
     *
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy(Role $role)
    {
        $result = $this->roleService->deleteRole($role);

        return response()->json($result);
    }
}

resources/views/pages/role/create.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Roles</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Create New Role</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        @if (session('error'))
                                            <div class="alert alert-danger alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('error') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        <form class="form-horizontal" action="{{ route('roles.store') }}" method="post">
                                            @csrf

                                            <div class="form-group row">
                                                <label for="title" class="col-sm-2 col-form-label">Name</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="name" name="name" value="{{ old('name') }}">
                                                    @error('name')
                                                        <div class="error">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-xs-12">
                                                    <button type="submit" class="btn btn-primary">Create</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/pages/role/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Roles</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Roles</a></li>
                            <li class="breadcrumb-item active">Edit</li>
                        </ol>
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Edit Role</h3>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        @if (session('message'))
                                            <div class="alert alert-success alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('message') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        @if (session('error'))
                                            <div class="alert alert-danger alert-dismissible fade show m-t-20 " role="alert">
                                                {{ session('error') }}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        @endif

                                        <form class="form-horizontal" action="{{ route('roles.update', $role->id) }}" method="post">
                                            @method('PUT')
                                            @csrf

                                            <div class="form-group row">
                                                <label for="title" class="col-sm-2 col-form-label">Name</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" id="name" name="name" value="{{ old('name') ?: $role->name }}">
                                                    @error('name')
                                                    <div class="error">
                                                        {{ $message }}
                                                    </div>
                                                    @enderror
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-xs-12">
                                                    <button type="submit" class="btn btn-primary">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/pages/role/index.blade.php
@extends('layouts.app')

@push('css')
    <link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Roles</h1>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Roles</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        @if (session('message'))
                            <div class="alert alert-success alert-dismissible fade show m-t-20 " role="alert">
                                {{ session('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h3 class="card-title">Available Roles</h3>
                                    <a href="{{ route('roles.create') }}"><button class="btn btn-primary">Create New Role</button></a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="role-table">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Created At</th>
                                            <th width="130px;">Action</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@push('js')
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
    <script>
        var deleteRole = function deleteRole(context) {
            var roleID = $(context).attr('data-id');
            var roleTitle = $(context).attr('data-title');

            swal({
                title: 'Are you sure want to delete role "' + roleTitle + '"?',
                text: "You will not be able to recover this role after deleted!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger m-l-10',
                confirmButtonText: 'Yes, delete it!'
            }).then(function (result) {
                if (!result.value) {
                    return;
                }

                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url: '/roles/' + roleID,
                    type: 'DELETE',
                    success: function(result) {
                        if (result) {
                            swal({
                                title: "Deleted!",
                                text: "Role " + roleTitle + " has been deleted.",
                                type: "success",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-success',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            }).then(function () {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: "Deleting Failed!",
                                text: "Failed to delete " + roleTitle,
                                type: "error",
                                showCancelButton: false,
                                confirmButtonClass: 'btn btn-danger',
                                confirmButtonText: "OK",
                                closeOnConfirm: false
                            }).then(function () {
                                location.reload();
                            });
                        }
                    }
                });
            })
        };

        $(function() {
            $('#role-table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                ajax: '{!! route('roles.get') !!}',
                columns: [
                    { data: 'id', name: 'id', searchable: false },
                    { data: 'name', name: 'name' },
                    { data: 'created_at', name: 'created_at', searchable: false },
                    { data: 'action', name: 'action', orderable: false, searchable: false }
                ],
                drawCallback: function() {
                    $('.delete-btn').on('click', function () {
                        deleteRole(this);
                    });
                }
            });
        });
    </script>
@endpush